name: janamaithri
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  camera: ^0.10.5+5
  chopper: ^7.0.9
  connectivity_plus: ^5.0.1
  dartz: ^0.10.1
  # device_id: ^0.2.0
  # device_info: ^2.0.3
  dio: ^5.3.3
  #dropdown_formfield: ^0.1.4
  dropdown_search: ^5.0.6
  fab_circular_menu: ^1.0.0
  file_picker: ^6.1.1
  # firebase_analytics: ^10.1.4
  # firebase_core: ^2.7.0
  # firebase_messaging: ^14.2.5
  firebase_analytics: ^10.6.3
  firebase_core: ^2.21.0
  firebase_messaging: ^14.7.3
  flutter:
    sdk: flutter
  flutter_background_service: ^5.0.3
  flutter_callkit_incoming: ^2.0.0+2
  flutter_datetime_picker: ^1.5.1
  flutter_downloader: ^1.10.5
  flutter_form_builder: ^9.1.1
  flutter_keyboard_visibility: ^5.4.1
  flutter_launcher_icons: ^0.13.1
  #flutter_local_notifications: ^9.6.1
  flutter_local_notifications: ^16.1.0
  flutter_map: ^6.0.1
  flutter_screenutil: ^5.7.0
  #flutter_xmllayout_helpers: ^0.0.9 
  font_awesome_flutter: ^10.4.0
  form_builder_validators: ^9.1.0
  gender_picker: ^1.1.0
  geolocator: ^10.1.0
  get: ^4.6.5
  get_storage: ^2.1.1
  gradient_floating_button: ^0.0.3
  html: ^0.15.4
  http: ^1.1.0
  image_picker: ^0.8.0+6
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  latlong2: ^0.9.0
  modal_progress_hud_nsn: ^0.4.0
  passwordfield: ^0.2.0
  path_provider: ^2.1.1
  percent_indicator: ^4.2.3
  permission_handler: ^11.0.1 
  provider: ^6.0.5
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  simple_animations: ^5.0.2
  simple_ripple_animation: ^0.0.7
  syncfusion_flutter_datepicker: ^23.1.44
  toggle_switch: ^2.1.0
  url_launcher: ^6.1.11
  web_socket_channel: ^2.4.0  
  

dependency_overrides:
  firebase_core_platform_interface: 5.0.0

dev_dependencies:
  #dart_code_metrics: ^5.6.0
  chewie_audio: ^1.5.0
  icons_launcher: ^2.1.0
  lint: ^2.0.20
  

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo_pic.png"
