part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const ROOT = _Paths.ROOT;
  static const LOGIN = _Paths.LOGIN;
  static const SIGNUP = _Paths.SIGNUP;
  static const PROFILE = _Paths.PROFILE;
  static const TICKET_DETAILS = _Paths.TICKET_DETAILS;
  static const ADD_TICKET = _Paths.ADD_TICKET;
  static const VEDIO_CALLING = _Paths.VEDIO_CALLING;
  static const TICKET_HISTORY = _Paths.TICKET_HISTORY;
  static const CALL_HISTORY = _Paths.CALL_HISTORY;
  static const RAIL_WAY_FORMS = _Paths.RAIL_WAY_FORMS;
  static const SOS_PAGE = _Paths.SOS_PAGE;
  static const REPORT_INCIDENT = _Paths.REPORT_INCIDENT;
  static const INTELLIGENCE = _Paths.INTELLIGENCE;
  static const INTRUDER_ALERT = _Paths.INTRUDER_ALERT;
  static const TRAIN_FORM = _Paths.TRAIN_FORM;
  static const LONELY_PASSENGER = _Paths.LONELY_PASSENGER;
  static const REPORT_INCIDENT_ON_TRAIN = _Paths.REPORT_INCIDENT_ON_TRAIN;
  static const REPORT_INCIDENT_ON_PLATFORM = _Paths.REPORT_INCIDENT_ON_PLATFORM;
  static const REPORT_INCIDENT_ON_TRACK = _Paths.REPORT_INCIDENT_ON_TRACK;
  static const RAIL_VOLUNTEER = _Paths.RAIL_VOLUNTEER;
  static const SHOPS_LABOUR = _Paths.SHOPS_LABOUR;
  static const STAFF_PORTERS = _Paths.STAFF_PORTERS;
  static const CAMERA = _Paths.CAMERA;
  static const RAIL_TICKET = _Paths.RAIL_TICKET;
  static const PAGE_LONELY = _Paths.PAGE_LONELY;
  static const PAGE_INCIDENT_TRAIN = _Paths.PAGE_INCIDENT_TRAIN;
  static const PAGE_INCIDENT_TRACK = _Paths.PAGE_INCIDENT_TRACK;
  static const PAGE_INCIDENT_PLATFORM = _Paths.PAGE_INCIDENT_PLATFORM;
  static const PAGE_INTELLIGENCE = _Paths.PAGE_INTELLIGENCE;
  static const PAGE_INTRUDER_ALERT = _Paths.PAGE_INTRUDER_ALERT;
  static const PAGE_RAIL_VOLUNTEER = _Paths.PAGE_RAIL_VOLUNTEER;
  static const PAGE_PORTER_REGISTRATION = _Paths.PAGE_PORTER_REGISTRATION;
  static const PAGE_LOST_PROPERTY = _Paths.PAGE_LOST_PROPERTY;
  static const PAGE_AWARENESS_CLASS = _Paths.PAGE_AWARENESS_CLASS;
  static const PAGE_SAFETY_TIP = _Paths.PAGE_SAFETY_TIP;
  static const PAGE_CONTACTS = _Paths.PAGE_CONTACTS;
  static const PAGE_SHOP_LABOURS = _Paths.PAGE_SHOP_LABOURS;
  static const PAGE_CONTACT_DETAILS = _Paths.PAGE_CONTACT_DETAILS;
  static const TICKET_HISTORY_DETAILS = _Paths.TICKET_HISTORY_DETAILS;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const ROOT = '/root';
  static const LOGIN = '/login';
  static const SIGNUP = '/signup';
  static const PROFILE = '/profile';
  static const TICKET_DETAILS = '/ticket-details';
  static const ADD_TICKET = '/add-ticket';
  static const VEDIO_CALLING = '/vedio-calling';
  static const TICKET_HISTORY = '/ticket-history';
  static const CALL_HISTORY = '/call-history';
  static const RAIL_WAY_FORMS = '/rail-way-forms';
  static const SOS_PAGE = '/sos-page';
  static const REPORT_INCIDENT = '/report-incident';
  static const INTELLIGENCE = '/intelligence';
  static const INTRUDER_ALERT = '/intruder-alert';
  static const TRAIN_FORM = '/train-form';
  static const LONELY_PASSENGER = '/lonely-passenger';
  static const REPORT_INCIDENT_ON_TRAIN = '/report-incident-on-train';
  static const REPORT_INCIDENT_ON_PLATFORM = '/report-incident-on-platform';
  static const REPORT_INCIDENT_ON_TRACK = '/report-incident-on-track';
  static const RAIL_VOLUNTEER = '/rail-volunteer';
  static const SHOPS_LABOUR = '/shops-labour';
  static const STAFF_PORTERS = '/staff-porters';
  static const CAMERA = '/camera';
  static const RAIL_TICKET = '/rail-ticket';
  static const PAGE_LONELY = '/page-lonely';
  static const PAGE_INCIDENT_TRAIN = '/page-incident-train';
  static const PAGE_INCIDENT_TRACK = '/page-incident-track';
  static const PAGE_INCIDENT_PLATFORM = '/page-incident-platform';
  static const PAGE_INTELLIGENCE = '/page-intelligence';
  static const PAGE_INTRUDER_ALERT = '/page-intruder-alert';
  static const PAGE_RAIL_VOLUNTEER = '/page-rail-volunteer';
  static const PAGE_PORTER_REGISTRATION = '/page-porter-registration';
  static const PAGE_LOST_PROPERTY = '/page-lost-property';
  static const PAGE_AWARENESS_CLASS = '/page-awareness-class';
  static const PAGE_SAFETY_TIP = '/page-safety-tip';
  static const PAGE_CONTACTS = '/page-contacts';
  static const PAGE_SHOP_LABOURS = '/page-shop-labours';
  static const PAGE_CONTACT_DETAILS = '/page-contact-details';
  static const TICKET_HISTORY_DETAILS = '/ticket-history-details';
}
